Add formatting check step to CI (#53)
* Add formatting check step to CI
* Format all code

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,6 +22,16 @@ jobs:
       - name: Test
         run: go test -v ./...
 
+      - name: Check Format
+        run: |
+          bad_files="$(gofmt -s -l .)"
+          if [[ -n $bad_files ]]; then
+              echo "::error::Some files are not formatted with 'gofmt -s'"
+              while IFS= read -r file_name; do
+                  echo "::error file=$file_name::$file_name is not formatted with 'gofmt -s'"
+              done <<< "$bad_files"
+              exit 1
+          fi
       - name: Lint
         uses: golangci/golangci-lint-action@v3
         with:
